# Generated by Django 5.2.7 on 2025-10-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(help_text='Name or identifier of the sender', max_length=255)),
                ('receiver', models.CharField(help_text='Name or phone number of the receiver', max_length=255)),
                ('message', models.TextField(help_text='Content of the SMS message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the SMS was sent')),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'ordering': ['-sent_at'],
            },
        ),
    ]
