# Generated by Django 5.2.7 on 2025-10-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livestream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the livestream event', max_length=255)),
                ('description', models.TextField(help_text='Description of the livestream event')),
                ('url', models.URLField(help_text='URL link to the livestream', max_length=500)),
                ('date', models.DateTimeField(help_text='Scheduled date and time of the livestream')),
            ],
            options={
                'verbose_name': 'Livestream',
                'verbose_name_plural': 'Livestreams',
                'ordering': ['-date'],
            },
        ),
    ]
