# Generated by Django 5.2.7 on 2025-10-21 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livestream',
            options={'ordering': ['-start_time'], 'verbose_name': 'Livestream', 'verbose_name_plural': 'Livestreams'},
        ),
        migrations.RemoveField(
            model_name='livestream',
            name='date',
        ),
        migrations.AddField(
            model_name='livestream',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Is this livestream currently active?'),
        ),
        migrations.AddField(
            model_name='livestream',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Scheduled start date and time of the livestream'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livestream',
            name='url',
            field=models.URLField(help_text='URL link to the livestream (YouTube, Facebook, etc.)', max_length=500),
        ),
    ]
