# Generated by Django 5.2.7 on 2025-10-21 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=255)),
                ('description', models.TextField(help_text='Event description')),
                ('event_type', models.CharField(choices=[('service', 'Church Service'), ('prayer', 'Prayer Meeting'), ('bible_study', 'Bible Study'), ('youth', 'Youth Meeting'), ('women', 'Women Fellowship'), ('men', 'Men Fellowship'), ('conference', 'Conference'), ('seminar', 'Seminar'), ('outreach', 'Outreach'), ('other', 'Other')], default='service', help_text='Type of event', max_length=50)),
                ('event_date', models.DateTimeField(help_text='Date and time of the event')),
                ('location', models.CharField(help_text='Event location/venue', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], default='present', help_text='Attendance status', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When attendance was marked')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.member')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-timestamp'],
                'unique_together': {('event', 'member')},
            },
        ),
    ]
