# Generated by Django 5.2.7 on 2025-10-21 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering_type', models.CharField(choices=[('general', 'General Offering'), ('thanksgiving', 'Thanksgiving'), ('building', 'Building Fund'), ('missions', 'Missions'), ('special', 'Special Offering'), ('other', 'Other')], default='general', help_text='Type of offering', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount collected', max_digits=10)),
                ('date_given', models.DateField(help_text='Date the offering was collected')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', help_text='Payment method used', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference', max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Has this been verified?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, help_text='Person who collected/recorded this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_offerings', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified this offering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_offerings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offering',
                'verbose_name_plural': 'Offerings',
                'ordering': ['-date_given'],
            },
        ),
        migrations.CreateModel(
            name='Tithe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in local currency', max_digits=10)),
                ('date_given', models.DateField(help_text='Date the tithe was given')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', help_text='Payment method used', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference (M-Pesa code, cheque number, etc.)', max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Has this been verified by an admin?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(help_text='Member who gave the tithe', on_delete=django.db.models.deletion.CASCADE, related_name='tithes', to='members.member')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified this tithe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tithes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tithe',
                'verbose_name_plural': 'Tithes',
                'ordering': ['-date_given'],
            },
        ),
    ]
