# Generated by Django 5.2.7 on 2025-10-21 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hymn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the hymn', max_length=255)),
                ('number', models.IntegerField(help_text='Hymn number in the hymnal', unique=True)),
                ('lyrics', models.TextField(help_text='Full lyrics of the hymn')),
                ('category', models.CharField(choices=[('worship', 'Worship'), ('praise', 'Praise'), ('thanksgiving', 'Thanksgiving'), ('prayer', 'Prayer'), ('communion', 'Communion'), ('christmas', 'Christmas'), ('easter', 'Easter'), ('other', 'Other')], default='worship', help_text='Category of the hymn', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hymns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hymn',
                'verbose_name_plural': 'Hymns',
                'ordering': ['number'],
            },
        ),
    ]
