# Generated by Django 5.2.7 on 2025-10-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Mark as urgent/important announcement'),
        ),
    ]
