# Generated by Django 5.2.7 on 2025-10-21 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full legal name', max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender', max_length=1)),
                ('age', models.IntegerField(blank=True, help_text='Age in years', null=True)),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('address', models.TextField(help_text='Physical address')),
                ('baptism_date', models.DateField(blank=True, help_text='Date of baptism', null=True)),
                ('membership_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred')], default='active', help_text='Current membership status', max_length=20)),
                ('joined_on', models.DateField(help_text='Date joined the church')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['full_name'],
            },
        ),
    ]
