# Generated by Django 5.2.7 on 2025-11-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='district',
            field=models.CharField(blank=True, help_text='District / fellowship group', max_length=120),
        ),
    ]
